export const countryCodes = [
  { code: "+1", country: "US", name: "United States" },
  { code: "+1", country: "CA", name: "Canada" },
  { code: "+44", country: "GB", name: "United Kingdom" },
  { code: "+61", country: "AU", name: "Australia" },
  { code: "+91", country: "IN", name: "India" },
  { code: "+20", country: "EG", name: "Egypt" },
  { code: "+966", country: "SA", name: "Saudi Arabia" },
  { code: "+971", country: "AE", name: "United Arab Emirates" },
  { code: "+965", country: "KW", name: "Kuwait" },
  { code: "+974", country: "QA", name: "Qatar" },
  { code: "+973", country: "BH", name: "Bahrain" },
  { code: "+968", country: "OM", name: "Oman" },
  { code: "+962", country: "JO", name: "Jordan" },
  { code: "+961", country: "LB", name: "Lebanon" },
  { code: "+963", country: "SY", name: "Syria" },
  { code: "+964", country: "IQ", name: "Iraq" },
  { code: "+967", country: "YE", name: "Yemen" },
  { code: "+212", country: "MA", name: "Morocco" },
  { code: "+213", country: "DZ", name: "Algeria" },
  { code: "+216", country: "TN", name: "Tunisia" },
  { code: "+218", country: "LY", name: "Libya" },
  { code: "+249", country: "SD", name: "Sudan" },
  { code: "+970", country: "PS", name: "Palestine" },
  { code: "+90", country: "TR", name: "Turkey" },
  { code: "+98", country: "IR", name: "Iran" },
  { code: "+92", country: "PK", name: "Pakistan" },
  { code: "+86", country: "CN", name: "China" },
  { code: "+81", country: "JP", name: "Japan" },
  { code: "+82", country: "KR", name: "South Korea" },
  { code: "+49", country: "DE", name: "Germany" },
  { code: "+33", country: "FR", name: "France" },
  { code: "+39", country: "IT", name: "Italy" },
  { code: "+34", country: "ES", name: "Spain" },
  { code: "+7", country: "RU", name: "Russia" },
  { code: "+55", country: "BR", name: "Brazil" },
  { code: "+52", country: "MX", name: "Mexico" },
  { code: "+54", country: "AR", name: "Argentina" },
  { code: "+27", country: "ZA", name: "South Africa" },
  { code: "+234", country: "NG", name: "Nigeria" },
  { code: "+254", country: "KE", name: "Kenya" },
  { code: "+31", country: "NL", name: "Netherlands" },
  { code: "+46", country: "SE", name: "Sweden" },
  { code: "+47", country: "NO", name: "Norway" },
  { code: "+45", country: "DK", name: "Denmark" },
  { code: "+358", country: "FI", name: "Finland" },
  { code: "+41", country: "CH", name: "Switzerland" },
  { code: "+43", country: "AT", name: "Austria" },
  { code: "+32", country: "BE", name: "Belgium" },
  { code: "+351", country: "PT", name: "Portugal" },
  { code: "+30", country: "GR", name: "Greece" },
  { code: "+48", country: "PL", name: "Poland" },
  { code: "+420", country: "CZ", name: "Czech Republic" }
].sort((a,b) => a.name.localeCompare(b.name));
