import React, { useState } from 'react';
import { Check, CircleCheck, Inbox, Loader2, LockKeyhole, Megaphone, Plus } from 'lucide-react';
import { auth, ADMIN_EMAIL } from '../../lib/firebase';
import { decideClaim, decideRequest, effectiveTier, identity, requestGrant, savePromo, saveSettings, sendAnnouncement, setPromoActive, updatePerson, updateTicket, type AdminRecord, type AdminSettings } from '../../lib/adminControl';
import { Badge, ErrorNote, fullDate, Modal, planName, requestName, shortDate } from './AdminUI';
export type AdminDialogValue = { kind: 'request' | 'claim' | 'person' | 'ticket' | 'promo-state' | 'promo-new' | 'settings' | 'announcement'; row?: AdminRecord };
type Props = { dialog: AdminDialogValue; busy: boolean; error: string; close: () => void; run: (action: () => Promise<{auditRecorded: boolean}>, message: string) => Promise<void>; users: Map<string, string>; bans: AdminRecord[]; settings: AdminSettings; previousSettings: AdminSettings; message: string; c: (en: string, ar: string) => string };
export default function AdminDialog({ dialog, busy, error, close, run, users, bans, settings, previousSettings, message, c }: Props) {
 const row = dialog.row;
 const [reason, setReason] = useState(''), [approve, setApprove] = useState(true), [verified, setVerified] = useState(false);
 const [personMode, setPersonMode] = useState<'grant' | 'suspend' | 'restore'>('grant'); const [tier, setTier] = useState('pro'); const [days, setDays] = useState(30);
 const [code, setCode] = useState(''), [discount, setDiscount] = useState(20), [reply, setReply] = useState('');
 const protectedPerson = row?.id === auth.currentUser?.uid || row?.email?.toLowerCase() === ADMIN_EMAIL.toLowerCase();
 const ban = bans.find(b => b.id === row?.id && b.active);
 let grantDescription = ''; if (row && dialog.kind === 'request') { try { const grant = requestGrant(row); grantDescription = `${planName(grant.tier)} · ${grant.days} days`; } catch { grantDescription = 'Unsupported request — approval unavailable'; } }
 const spinner = busy ? <Loader2 className="ac-spin" size={16}/> : null;
 const title = { request: c('Review request', 'مراجعة الطلب'), claim: c('Review referral', 'مراجعة الإحالة'), person: c('Manage account', 'إدارة الحساب'), ticket: c('Support conversation', 'محادثة الدعم'), 'promo-state': c('Update promotion', 'تعديل العرض'), 'promo-new': c('Create a promotion', 'إنشاء عرض'), settings: c('Confirm settings', 'تأكيد الإعدادات'), announcement: c('Preview announcement', 'معاينة الإعلان') }[dialog.kind];
 return <Modal title={title} busy={busy} close={close}>
 {(dialog.kind === 'request' || dialog.kind === 'claim') && row && <>
  <div className="ac-review-identity"><span className="ac-row-icon"><Inbox size={23}/></span><div><strong>{users.get(row.userId || row.newUid) || row.email || row.userId || row.newUid}</strong><small>{requestName(row)}</small></div><Badge tone={row.status === 'pending' ? 'warm' : ''}>{row.status}</Badge></div>
  <dl className="ac-detail-grid"><div><dt>Request ID</dt><dd>{row.id}</dd></div><div><dt>Submitted</dt><dd>{fullDate(row.createdAt)}</dd></div><div><dt>{dialog.kind === 'claim' ? 'Referral code' : 'Access to grant'}</dt><dd>{dialog.kind === 'claim' ? row.code : grantDescription}</dd></div><div><dt>{dialog.kind === 'claim' ? 'New account' : 'Promo code'}</dt><dd>{dialog.kind === 'claim' ? row.newUid : row.promoCode || 'None'}</dd></div></dl>
  {row.status === 'pending' ? <form onSubmit={e => { e.preventDefault(); if (approve && !verified) return; void run(() => dialog.kind === 'claim' ? decideClaim(row.id, approve, reason) : decideRequest(row.id, approve, reason), c('Decision saved.', 'تم حفظ القرار.')); }}><fieldset disabled={busy}>
   <div className="ac-choice"><button type="button" aria-pressed={approve} onClick={() => setApprove(true)}>Approve</button><button type="button" aria-pressed={!approve} onClick={() => setApprove(false)}>Reject</button></div>
   {approve && <label className="ac-check"><input type="checkbox" checked={verified} onChange={e => setVerified(e.target.checked)}/><span>{row.kind === 'subscription' ? c('I verified the payment or promo eligibility outside this request.', 'تحققت من الدفع أو أهلية العرض خارج هذا الطلب.') : c('I reviewed this account and verified its eligibility.', 'راجعت الحساب وتحققت من أهليته.')}</span></label>}
   <label className="ac-field">{c('Decision note', 'سبب القرار')}<textarea value={reason} onChange={e => setReason(e.target.value)} maxLength={1000} required rows={3} placeholder="Add a short review note…"/></label>
   <button className="ac-primary ac-submit" disabled={busy || !reason.trim() || (approve && !verified) || (approve && grantDescription.startsWith('Unsupported'))}>{spinner || <Check size={16}/>} {approve ? c('Confirm approval', 'تأكيد الموافقة') : c('Confirm rejection', 'تأكيد الرفض')}</button>
  </fieldset></form> : <div className="ac-inline-note"><CircleCheck size={20}/><div><p>{row.decisionNote || row.rejectionReason || 'This request has been decided.'}</p><small>{row.decidedBy} · {fullDate(row.decidedAt)}</small></div></div>}
 </>}
 {dialog.kind === 'person' && row && <>
  <div className="ac-review-identity"><span className="ac-avatar">{String(identity(row)).slice(0, 2).toUpperCase()}</span><div><strong>{identity(row)}</strong><small>{row.id}</small></div></div>
  <dl className="ac-detail-grid"><div><dt>Effective plan</dt><dd>{planName(effectiveTier(row))}</dd></div><div><dt>Expiry</dt><dd>{shortDate(row.subscriptionExpiry)}</dd></div><div><dt>Access</dt><dd>{ban ? 'Suspended' : 'Allowed'}</dd></div><div><dt>Joined</dt><dd>{shortDate(row.createdAt)}</dd></div></dl>
  {ban && <p className="ac-inline-note">{ban.reason}</p>}
  {protectedPerson ? <div className="ac-inline-note"><LockKeyhole size={19}/>{c('This administrator account is protected.', 'هذا الحساب الإداري محمي.')}</div> : <form onSubmit={e => { e.preventDefault(); void run(() => updatePerson(row.id, personMode, { tier, days, reason }), c('Account updated.', 'تم تحديث الحساب.')); }}><fieldset disabled={busy}>
   <label className="ac-field">{c('Action', 'الإجراء')}<select value={personMode} onChange={e => setPersonMode(e.target.value as typeof personMode)}><option value="grant">Change membership</option><option value={ban ? 'restore' : 'suspend'}>{ban ? 'Restore access' : 'Suspend access'}</option></select></label>
   {personMode === 'grant' && <><div className="ac-form-grid"><label className="ac-field">Plan<select value={tier} onChange={e => setTier(e.target.value)}>{['pro', 'enterprise', 'free'].map(p => <option value={p} key={p}>{planName(p)}</option>)}</select></label><label className="ac-field">Days<input type="number" min={1} max={3650} required disabled={tier === 'free'} value={days} onChange={e => setDays(Number(e.target.value))}/></label></div><p className="ac-muted">{tier === 'free' ? 'Paid access ends immediately. Scan history is retained.' : 'Adds days to the remaining subscription. Active SOC accounts keep SOC access when granted Pro.'}</p></>}
   <label className="ac-field">Reason<textarea required rows={3} maxLength={1000} value={reason} onChange={e => setReason(e.target.value)}/></label><button className="ac-primary ac-submit" disabled={busy || !reason.trim()}>{spinner}{c('Confirm account change', 'تأكيد تعديل الحساب')}</button>
  </fieldset></form>}
 </>}
 {dialog.kind === 'ticket' && row && <><div className="ac-section-heading"><h3>{row.subject}</h3><Badge>{row.status}</Badge></div><p className="ac-muted">{row.email || row.userId} · {row.category}</p>
  <div className="ac-conversation"><article><small>{shortDate(row.createdAt)} · User</small><p>{row.message}</p></article>{(row.replies || []).map((r: any, i: number) => <article data-admin={r.from === 'admin'} key={i}><small>{r.from === 'admin' ? 'Administrator' : 'User'} · {fullDate(r.timestamp)}</small><p>{r.message}</p></article>)}</div>
  {row.status !== 'closed' && <form onSubmit={e => { e.preventDefault(); void run(() => updateTicket(row.id, reply), c('Reply saved.', 'تم حفظ الرد.')); }}><fieldset disabled={busy}><label className="ac-field">Reply<textarea required maxLength={4000} rows={4} value={reply} onChange={e => setReply(e.target.value)}/></label><div className="ac-dialog-actions"><button type="button" className="ac-button" onClick={() => void run(() => updateTicket(row.id, '', true), c('Ticket closed.', 'تم إغلاق التذكرة.'))}>Resolve ticket</button><button className="ac-primary" disabled={busy || !reply.trim()}>{spinner}Save reply</button></div></fieldset></form>}
 </>}
 {dialog.kind === 'promo-new' && <form onSubmit={e => { e.preventDefault(); void run(() => savePromo(code, discount, tier), c('Promotion created.', 'تم إنشاء العرض.')); }}><fieldset disabled={busy}><p className="ac-muted">{c('Codes apply to subscription requests. Activation still requires review.', 'الأكواد تستخدم في طلبات الاشتراك. التفعيل يحتاج مراجعة.')}</p><label className="ac-field">Code<input required maxLength={32} pattern="[A-Z0-9_-]+" value={code} placeholder="WELCOME20" onChange={e => setCode(e.target.value.toUpperCase())}/></label><div className="ac-form-grid"><label className="ac-field">Discount (%)<input type="number" required min={1} max={100} value={discount} onChange={e => setDiscount(Number(e.target.value))}/></label><label className="ac-field">Eligible plan<select value={tier} onChange={e => setTier(e.target.value)}>{['pro', 'enterprise', 'all'].map(p => <option key={p} value={p}>{planName(p)}</option>)}</select></label></div><button className="ac-primary ac-submit" disabled={busy || !code.trim()}>{spinner || <Plus size={16}/>}Create code</button></fieldset></form>}
 {dialog.kind === 'promo-state' && row && <><p className="ac-dialog-copy">{row.active ? 'Pause' : 'Enable'} <strong>{row.code || row.id}</strong>?</p><p className="ac-muted">{row.active ? 'New uses of this code will be blocked. Existing requests still need manual review.' : 'The code will be available for eligible subscription requests.'}</p><button className="ac-primary ac-submit" disabled={busy} onClick={() => void run(() => setPromoActive(row.id, !row.active), c('Promotion updated.', 'تم تحديث العرض.'))}>{spinner}Confirm change</button></>}
 {dialog.kind === 'settings' && <><p className="ac-muted">{c('These settings affect the user interface after its configuration refreshes.', 'هذه الإعدادات تؤثر على الواجهة عند تحديث إعداداتها.')}</p><dl className="ac-detail-grid">{(Object.keys(settings) as (keyof AdminSettings)[]).map(k => <div key={k}><dt>{k === 'maintenanceMode' ? 'Workspace maintenance' : 'AI assistant maintenance'}</dt><dd>{previousSettings[k] ? 'On' : 'Off'} → <strong>{settings[k] ? 'On' : 'Off'}</strong></dd></div>)}</dl><button className="ac-primary ac-submit" disabled={busy} onClick={() => void run(() => saveSettings(settings, previousSettings), c('Platform settings saved.', 'تم حفظ إعدادات المنصة.'))}>{spinner}Save settings</button></>}
 {dialog.kind === 'announcement' && <><div className="ac-announcement-preview"><Megaphone size={21}/><strong>JoeScan announcement</strong><p>{row?.message || message}</p></div><p className="ac-muted">{c('This creates in-app notifications for registered accounts. No emails are sent.', 'ينشئ إشعارات داخل التطبيق للحسابات المسجلة، بدون إرسال بريد إلكتروني.')}</p><button className="ac-primary ac-submit" disabled={busy} onClick={() => void run(() => sendAnnouncement(row?.message || message, row?.id), c('Announcement delivered.', 'تم تسليم الإعلان.'))}>{spinner}{row ? c('Resume delivery', 'استكمال الإرسال') : c('Send announcement', 'إرسال الإعلان')}</button></>}
 {error && <ErrorNote message={error}/>}
 </Modal>;
}
