import React, { useState } from 'react';
import { Activity, ArrowDownToLine, ArrowUpRight, ChevronRight, Megaphone, Search, Settings2, ShieldCheck } from 'lucide-react';
import { newest, SECTION_NAMES, type AdminRecord, type AdminSection, type AdminSettings } from '../../lib/adminControl';
import type { AdminData } from '../../hooks/useAdminCenter';
import type { AdminDialogValue } from './AdminDialog';
import { Badge, Empty, Pager, fullDate, shortDate } from './AdminUI';
export type PlatformPanel = 'settings' | 'activity' | 'announcements' | 'exports';
type Props = { data: AdminData; errors: Partial<Record<AdminSection, string>>; panel: PlatformPanel; setPanel: (p: PlatformPanel) => void; settings: AdminSettings; setSettings: React.Dispatch<React.SetStateAction<AdminSettings>>; message: string; setMessage: (s: string) => void; open: (d: AdminDialogValue) => void; unavailable: (s: AdminSection[]) => React.ReactNode; c: (en: string, ar: string) => string };
export function exportAdminRecords(section: AdminSection, rows: AdminRecord[]) {
 const fields: Partial<Record<AdminSection, string[]>> = { users: ['id', 'name', 'email', 'tier', 'subscriptionExpiry', 'createdAt'], bans: ['id', 'active', 'reason', 'bannedAt', 'restoredAt'], requests: ['id', 'userId', 'kind', 'tier', 'status', 'createdAt', 'decidedAt'], claims: ['id', 'newUid', 'code', 'status', 'createdAt'], activity: ['id', 'action', 'email', 'details', 'timestamp', 'provenance'], tickets: ['id', 'email', 'subject', 'category', 'status', 'createdAt'], promos: ['id', 'discount', 'targetTier', 'active', 'createdAt'] };
 return { exportedAt: new Date().toISOString(), scope: section === 'activity' ? 'Latest 100 events' : section === 'requests' || section === 'claims' ? 'All pending and latest 50 records' : 'Loaded records', records: rows.map(row => Object.fromEntries((fields[section] || []).filter(k => row[k] !== undefined).map(k => [k, row[k]]))) };
}
export default function AdminPlatform({ data, errors, panel, setPanel, settings, setSettings, message, setMessage, open, unavailable, c }: Props) {
 const [search, setSearch] = useState(''), [filter, setFilter] = useState('all'), [page, setPage] = useState(1);
 const blocked = (sections: AdminSection[]) => sections.some(s => errors[s]);
 const activity = data.activity.filter(r => (!search.trim() || [r.email, r.details, r.action, r.targetUser].join(' ').toLowerCase().includes(search.trim().toLowerCase())) && (filter === 'all' || r.action === filter));
 const p = Math.min(page, Math.max(1, Math.ceil(activity.length / 8)));
 const download = (section: AdminSection) => {
  const href = URL.createObjectURL(new Blob([JSON.stringify(exportAdminRecords(section, data[section] as AdminRecord[]), null, 2)], { type: 'application/json' }));
  const link = document.createElement('a'); link.href = href; link.download = `joescan-${section}-${new Date().toISOString().slice(0, 10)}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(href), 1000);
 };
 return <div className="ac-platform"><nav className="ac-subnav" aria-label="Platform sections">{[{ id: 'settings', title: c('Settings', 'الإعدادات'), icon: Settings2 }, { id: 'activity', title: c('Activity log', 'سجل النشاط'), icon: Activity }, { id: 'announcements', title: c('Announcements', 'الإعلانات'), icon: Megaphone }, { id: 'exports', title: c('Export data', 'تصدير البيانات'), icon: ArrowDownToLine }].map(({ id, title, icon: Icon }) => <button key={id} aria-current={panel === id ? 'page' : undefined} onClick={() => { setPanel(id as PlatformPanel); setSearch(''); setFilter('all'); setPage(1); }}><Icon size={17}/>{title}<ChevronRight size={14}/></button>)}</nav><div className="ac-platform-body">
 {panel === 'settings' && <section className="ac-panel"><div className="ac-section-heading"><div><h2>{c('Platform settings', 'إعدادات المنصة')}</h2><p>{c('Review changes before saving them.', 'راجع التغييرات قبل حفظها.')}</p></div><Settings2 size={22}/></div>{blocked(['settings']) ? unavailable(['settings']) : <>
  <div className="ac-setting-row"><div><strong>{c('Workspace maintenance', 'صيانة مساحة العمل')}</strong><p>{c('Shows the maintenance screen to non-admin users when their app reloads.', 'يعرض شاشة الصيانة للمستخدمين غير المسؤولين عند إعادة تحميل التطبيق.')}</p></div><button type="button" role="switch" aria-checked={settings.maintenanceMode} aria-label="Workspace maintenance" className="ac-switch" onClick={() => setSettings(s => ({ ...s, maintenanceMode: !s.maintenanceMode }))}><span/></button></div>
  <div className="ac-setting-row"><div><strong>{c('AI assistant maintenance', 'صيانة المساعد الذكي')}</strong><p>{c('Displays the AI maintenance notice and disables the assistant chat.', 'يعرض تنبيه صيانة ويوقف واجهة محادثة المساعد.')}</p></div><button type="button" role="switch" aria-checked={settings.aiMaintenanceMode} aria-label="AI assistant maintenance" className="ac-switch" onClick={() => setSettings(s => ({ ...s, aiMaintenanceMode: !s.aiMaintenanceMode }))}><span/></button></div>
  <div className="ac-save-row"><span className="ac-muted">{JSON.stringify(settings) === JSON.stringify(data.settings) ? c('No unsaved changes', 'لا توجد تغييرات غير محفوظة') : c('You have unsaved changes', 'لديك تغييرات غير محفوظة')}</span><button className="ac-primary" disabled={JSON.stringify(settings) === JSON.stringify(data.settings)} onClick={() => open({ kind: 'settings' })}>{c('Review changes', 'مراجعة التغييرات')}</button></div>
  <div className="ac-inline-note"><ShieldCheck size={19}/><p>{c('Plan quotas are enforced by the service. Only connected controls are shown here.', 'حدود الباقات يطبقها الخادم. تظهر هنا الإعدادات المرتبطة بوظائف فعلية فقط.')}</p></div>
 </>}</section>}
 {panel === 'activity' && <section className="ac-panel"><div className="ac-section-heading"><div><h2>{c('Activity log', 'سجل النشاط')}</h2><p>{c('Latest 100 recorded events, with source labels preserved.', 'آخر 100 حدث مسجل، مع توضيح مصدر كل حدث.')}</p></div><Activity size={21}/></div>{blocked(['activity']) ? unavailable(['activity']) : <>
  <div className="ac-toolbar"><label className="ac-search"><Search size={17}/><input aria-label="Search activity" placeholder="Search activity…" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }}/></label><select aria-label="Filter events" value={filter} onChange={e => { setFilter(e.target.value); setPage(1); }}><option value="all">All events</option>{Array.from(new Set(data.activity.map(r => String(r.action || 'unknown')))).map(a => <option key={a} value={a}>{a.replaceAll('_', ' ')}</option>)}</select></div>
  {activity.slice((p - 1) * 8, p * 8).map(a => <div className="ac-log-row" key={a.id}><div><Badge>{a.action?.replaceAll('_', ' ')}</Badge><time>{fullDate(a.timestamp)}</time></div><p>{a.details || 'No details recorded'}</p><small>{a.email || a.userId}{a.provenance ? ` · ${a.provenance}` : ''}</small></div>)}{!activity.length && <Empty title={c('No matching events.', 'لا توجد أحداث مطابقة.')}/>}<Pager page={page} total={activity.length} onChange={setPage}/>
 </>}</section>}
 {panel === 'announcements' && <section className="ac-panel"><div className="ac-section-heading"><div><h2>{c('Announcements', 'الإعلانات')}</h2><p>{c('Send an in-app notification to registered accounts.', 'أرسل إشعارًا داخل التطبيق للحسابات المسجلة.')}</p></div><Megaphone size={21}/></div>{blocked(['announcements', 'users']) ? unavailable(['announcements', 'users']) : <>
  <label className="ac-field">{c('Your message', 'رسالتك')}<textarea value={message} maxLength={1000} rows={4} onChange={e => setMessage(e.target.value)} placeholder={c('What should your users know?', 'ما الذي تريد إبلاغ المستخدمين به؟')}/></label><div className="ac-save-row"><span className="ac-muted">{message.length} / 1000</span><button className="ac-primary" disabled={!message.trim() || !data.users.length} onClick={() => open({ kind: 'announcement' })}>{c('Preview announcement', 'معاينة الإعلان')}</button></div>
  <h3 className="ac-small-heading">{c('Recent announcements', 'آخر الإعلانات')}</h3>{newest(data.announcements).map(a => <div className="ac-log-row" key={a.id}><div><Badge tone={a.status === 'sent' ? 'lime' : 'warm'}>{a.status || 'Legacy record'}</Badge><time>{shortDate(a.createdAt)}</time></div><p>{a.message}</p><small>{Number(a.recipientCount) || 0} {c('delivery records', 'سجل تسليم')}</small>{a.status === 'sending' && <button className="ac-text-button" onClick={() => { setMessage(a.message); open({ kind: 'announcement', row: a }); }}>{c('Resume delivery', 'استكمال الإرسال')}<ArrowUpRight size={14}/></button>}</div>)}{!data.announcements.length && <p className="ac-muted">{c('No announcements yet.', 'لا توجد إعلانات بعد.')}</p>}
 </>}</section>}
 {panel === 'exports' && <section className="ac-panel"><div className="ac-section-heading"><div><h2>{c('Export records', 'تصدير السجلات')}</h2><p>{c('Download a JSON snapshot of the records loaded here.', 'حمّل نسخة JSON من البيانات المعروضة هنا.')}</p></div><ArrowDownToLine size={22}/></div><div className="ac-export-grid">{(['users', 'requests', 'claims', 'tickets', 'promos', 'bans', 'activity'] as AdminSection[]).map(s => <button key={s} disabled={!!errors[s]} onClick={() => download(s)}><div><strong>{SECTION_NAMES[s]}</strong><small>{errors[s] ? c('Unavailable', 'غير متاح') : `${(data[s] as AdminRecord[]).length} records`}</small></div><ArrowDownToLine size={18}/></button>)}</div><p className="ac-muted">{c('Account exports contain identity and plan fields only. Scan contents and authentication secrets are excluded.', 'تصدير الحسابات يقتصر على الهوية والباقة. لا يشمل محتوى الفحوصات أو أسرار المصادقة.')}</p></section>}
 </div></div>;
}
