import React, { useEffect, useRef, useState } from 'react';
import { AlertCircle, ArrowUpRight, Ban, Check, CreditCard, Inbox, Loader2, LockKeyhole, MessageSquare, Plus, RefreshCw, Search, Settings2, ShieldCheck, SlidersHorizontal, Tag, Users, X } from 'lucide-react';
import { useLanguage } from '../contexts/LanguageContext';
import { useAdminCenter } from '../hooks/useAdminCenter';
import { effectiveTier, identity, newest, SECTION_NAMES, type AdminRecord, type AdminSection, type AdminSettings } from '../lib/adminControl';
import { Badge, Empty, Pager, planName, requestName, shortDate } from './admin/AdminUI';
import AdminDialog, { type AdminDialogValue } from './admin/AdminDialog';
import AdminPlatform, { type PlatformPanel } from './admin/AdminPlatform';
import '../styles/focus-admin.css';
type Tab = 'overview' | 'requests' | 'people' | 'support' | 'promotions' | 'platform';
export default function AdminDashboard() {
 const { lang, dir } = useLanguage(); const c = (en: string, ar: string) => lang === 'ar' ? ar : en;
 const { data, errors, loading, accessError, updatedAt, refresh } = useAdminCenter();
 const [tab, setTab] = useState<Tab>('overview'), [panel, setPanel] = useState<PlatformPanel>('settings');
 const [search, setSearch] = useState(''), [filter, setFilter] = useState('all'), [page, setPage] = useState(1);
 const [dialog, setDialog] = useState<AdminDialogValue | null>(null), [busy, setBusy] = useState(false); const lock = useRef(false);
 const [feedback, setFeedback] = useState(''), [formError, setFormError] = useState(''), [message, setMessage] = useState('');
 const [settings, setSettings] = useState<AdminSettings>(data.settings);
 useEffect(() => { setSettings(data.settings); }, [data.settings]);
 const open = (value: AdminDialogValue) => { setDialog(value); setFormError(''); };
 const navigate = (value: Tab, nextPanel?: PlatformPanel) => { setTab(value); if (nextPanel) setPanel(nextPanel); setSearch(''); setFilter(value === 'requests' ? 'pending' : 'all'); setPage(1); };
 const run = async (action: () => Promise<{ auditRecorded: boolean }>, success: string) => {
  if (lock.current) return; lock.current = true; setBusy(true); setFormError(''); setFeedback('');
  try { const result = await action(); setFeedback(success + (result.auditRecorded ? '' : c(' The change was saved, but its activity log could not be recorded.', ' تم الحفظ، لكن تعذر تسجيل الحدث في سجل النشاط.'))); setDialog(null); setMessage(''); await refresh(); }
  catch (err: any) { setFormError(err?.code ? c('The action could not be saved. Check access and connection, then retry.', 'تعذر حفظ الإجراء. راجع الاتصال والصلاحيات وحاول مجددًا.') : err?.message || c('Unable to complete the action.', 'تعذر إتمام الإجراء.')); }
  finally { setBusy(false); lock.current = false; }
 };
 const activeBans = data.bans.filter(b => b.active), suspended = new Set(activeBans.map(b => b.id));
 const pending = [...data.requests, ...data.claims].filter(r => r.status === 'pending').length, waiting = data.tickets.filter(t => t.status === 'open').length;
 const userMap = new Map<string, string>(data.users.map(u => [u.id, String(identity(u))]));
 const queue = newest([...data.requests, ...data.claims.map(r => ({ ...r, kind: 'claim', userId: r.newUid }))]).sort((a, b) => Number(b.status === 'pending') - Number(a.status === 'pending'));
 const matches = (row: AdminRecord, keys: string[]) => !search.trim() || keys.map(k => row[k] || '').join(' ').toLowerCase().includes(search.trim().toLowerCase());
 const windowRows = (rows: AdminRecord[]) => { const p = Math.min(page, Math.max(1, Math.ceil(rows.length / 8))); return rows.slice((p - 1) * 8, p * 8); };
 const blocked = (sections: AdminSection[]) => sections.some(s => errors[s]);
 const unavailableView = (sections: AdminSection[]) => <div className="ac-unavailable" role="alert"><AlertCircle size={22}/><h3>{c('This section is unavailable', 'تعذر تحميل هذا القسم')}</h3><p>{sections.filter(s => errors[s]).map(s => SECTION_NAMES[s]).join(', ')}. {c('Retry to load current records.', 'أعد المحاولة لتحميل البيانات الحالية.')}</p><button className="ac-button" disabled={loading || busy} onClick={refresh}><RefreshCw size={14}/>{c('Retry', 'إعادة المحاولة')}</button></div>;
 const people = newest(data.users).filter(u => matches(u, ['email', 'name', 'id']) && (filter === 'all' || (filter === 'suspended' ? suspended.has(u.id) : effectiveTier(u) === filter)));
 const requests = queue.filter(r => matches({ ...r, account: userMap.get(r.userId) || r.email }, ['account', 'id', 'kind', 'userId', 'code']) && (filter === 'all' || r.status === filter));
 const tickets = newest(data.tickets).filter(r => matches(r, ['email', 'subject', 'id']) && (filter === 'all' || r.status === filter));
 const promos = newest(data.promos).filter(r => matches(r, ['id', 'code']) && (filter === 'all' || (filter === 'active' ? r.active : !r.active)));
 const nav: { id: Tab; label: string; icon: any }[] = [
  { id: 'overview', label: c('Overview', 'نظرة عامة'), icon: SlidersHorizontal }, { id: 'requests', label: c('Requests', 'الطلبات'), icon: Inbox }, { id: 'people', label: c('People', 'المستخدمون'), icon: Users }, { id: 'support', label: c('Support', 'الدعم'), icon: MessageSquare }, { id: 'promotions', label: c('Promotions', 'العروض'), icon: Tag }, { id: 'platform', label: c('Platform', 'المنصة'), icon: Settings2 },
 ];
 const toolbar = (placeholder: string, options: [string, string][]) => <div className="ac-toolbar"><label className="ac-search"><Search size={17}/><input aria-label={placeholder} placeholder={placeholder} value={search} onChange={e => { setSearch(e.target.value); setPage(1); }}/></label><select aria-label="Filter records" value={filter} onChange={e => { setFilter(e.target.value); setPage(1); }}>{options.map(([v, name]) => <option value={v} key={v}>{name}</option>)}</select></div>;
 const queueRows = (rows: AdminRecord[]) => rows.map(r => <div className="ac-queue-row" key={r.kind + r.id}><span className="ac-row-icon"><CreditCard size={18}/></span><div className="ac-row-main"><strong>{userMap.get(r.userId) || r.email || r.userId || r.id}</strong><small>{requestName(r)} · {shortDate(r.createdAt)}</small></div><Badge tone={r.status === 'pending' ? 'warm' : ''}>{r.status}</Badge><button className="ac-text-button" onClick={() => open({ kind: r.kind === 'claim' ? 'claim' : 'request', row: r })}>{c('Review', 'مراجعة')}<ArrowUpRight size={14}/></button></div>);
 return <div className="focus-admin" dir={dir}>
 <div inert={dialog ? true : undefined}>
  <div className="ac-header"><div><span className="ac-eyebrow"><ShieldCheck size={14}/> JOESCAN / SYSTEM ADMINISTRATION</span><h1>{c('System Command Center', 'مركز إدارة النظام')}</h1><p>{c('A clear view. Every decision within reach.', 'رؤية واضحة للنظام، وكل قرار في مكانه.')}</p></div><div className="ac-header-actions"><Badge><LockKeyhole size={12}/>{c('Administrator', 'مسؤول النظام')}</Badge><button className="ac-button" onClick={refresh} disabled={loading || busy}><RefreshCw size={15} className={loading ? 'ac-spin' : ''}/>{c('Refresh', 'تحديث')}</button></div></div>
  {accessError ? <div className="ac-unavailable" role="alert"><LockKeyhole size={25}/><h2>{c('Administrator access required', 'يلزم حساب مسؤول')}</h2><p>{accessError}</p><button className="ac-button" disabled={loading} onClick={refresh}>{c('Retry session', 'إعادة التحقق')}</button></div> : <>
   <nav className="ac-nav" aria-label="Administration sections">{nav.map(({ id, label, icon: Icon }) => <button aria-current={tab === id ? 'page' : undefined} key={id} onClick={() => navigate(id)}><Icon size={16}/>{label}{id === 'requests' && !blocked(['requests', 'claims']) && pending > 0 && <span>{pending}</span>}</button>)}</nav>
   {feedback && <div role="status" className="ac-feedback"><Check size={17}/><p>{feedback}</p><button className="ac-icon" aria-label="Dismiss message" onClick={() => setFeedback('')}><X size={16}/></button></div>}
   {Object.keys(errors).length > 0 && <div className="ac-data-warning" role="status"><AlertCircle size={16}/>{c('Some records could not be loaded. Affected sections show an error.', 'تعذر تحميل بعض البيانات. ستظهر رسالة في الأقسام المتأثرة.')}</div>}
   {loading ? <div className="ac-loading" role="status"><Loader2 size={25} className="ac-spin"/><p>{c('Loading command center…', 'جاري تحميل مركز الإدارة…')}</p></div> : <div className="ac-content" key={tab + panel}>
   {tab === 'overview' && <>
    <div className="ac-metrics">{[{ label: c('Registered accounts', 'الحسابات المسجلة'), value: data.users.length, icon: Users, sections: ['users'] }, { label: c('Awaiting review', 'بانتظار المراجعة'), value: pending, icon: Inbox, sections: ['requests', 'claims'] }, { label: c('Open support tickets', 'تذاكر دعم مفتوحة'), value: waiting, icon: MessageSquare, sections: ['tickets'] }, { label: c('Suspended accounts', 'حسابات موقوفة'), value: activeBans.length, icon: Ban, sections: ['bans'] }].map((metric, i) => <div key={metric.label}><span className="ac-metric-label"><metric.icon size={16}/>{metric.label}</span><strong>{blocked(metric.sections as AdminSection[]) ? '—' : metric.value.toLocaleString()}</strong><span className="ac-metric-foot">{blocked(metric.sections as AdminSection[]) ? c('Unavailable', 'غير متاح') : ['ACCOUNT RECORDS', 'DECISIONS TO MAKE', 'WAITING FOR A REPLY', 'ACCESS RESTRICTED'][i]}</span></div>)}</div>
    <div className="ac-overview-grid"><section className="ac-panel ac-inbox"><div className="ac-section-heading"><div><span className="ac-eyebrow">01 / {c('NEXT IN LINE', 'الخطوة التالية')}</span><h2>{c('Your review queue', 'طلبات تحتاج مراجعتك')}</h2></div><button className="ac-text-button" onClick={() => navigate('requests')}>{c('View requests', 'كل الطلبات')}<ArrowUpRight size={15}/></button></div>{blocked(['requests', 'claims']) ? unavailableView(['requests', 'claims']) : pending ? <div>{queueRows(queue.filter(r => r.status === 'pending').slice(0, 4))}</div> : <Empty title={c('You’re all caught up.', 'كل الطلبات تمت مراجعتها.')} detail={c('New subscription and referral requests will appear here.', 'طلبات الاشتراك والإحالات الجديدة هتظهر هنا.')}/>}<div className="ac-inbox-foot"><ShieldCheck size={15}/>{c('Subscriptions activate only after your review.', 'الاشتراكات تتفعل بعد مراجعتك فقط.')}</div></section>
    <section className="ac-panel ac-plan-panel"><div className="ac-section-heading"><div><span className="ac-eyebrow">02 / {c('MEMBERSHIP', 'الاشتراكات')}</span><h2>{c('Plans at a glance', 'نظرة على الباقات')}</h2></div><CreditCard size={20}/></div>{blocked(['users']) ? unavailableView(['users']) : <><div className="ac-plan-count"><strong>{data.users.filter(u => effectiveTier(u) !== 'free').length}</strong><span>{c('active paid-tier accounts', 'حسابات بباقات مدفوعة سارية')}</span></div><div className="ac-plan-bar" aria-hidden="true">{['free', 'pro', 'enterprise'].map((p, i) => <span key={p} style={{ flex: data.users.filter(u => effectiveTier(u) === p).length || (data.users.length ? 0 : 1), background: ['#405139', '#b7ff72', '#89afa2'][i] }}/>)}</div><dl className="ac-plan-legend">{['free', 'pro', 'enterprise'].map((p, i) => <div key={p}><dt><i style={{ background: ['#405139', '#b7ff72', '#89afa2'][i] }}/>{planName(p)}</dt><dd>{data.users.filter(u => effectiveTier(u) === p).length}</dd></div>)}</dl><p className="ac-muted">{c('Includes trials and grants. These counts show access, not payment revenue.', 'يشمل التجارب والمنح. الأعداد تعبر عن صلاحيات الحسابات، وليست إيرادات.')}</p></>}</section></div>
    <div className="ac-overview-bottom"><section className="ac-panel"><div className="ac-section-heading"><h2>{c('Recent activity', 'آخر النشاطات')}</h2><button className="ac-text-button" onClick={() => navigate('platform', 'activity')}>{c('Open log', 'فتح السجل')}<ArrowUpRight size={14}/></button></div>{blocked(['activity']) ? unavailableView(['activity']) : data.activity.length ? data.activity.slice(0, 3).map(a => <div className="ac-event" key={a.id}><span className="ac-event-dot"/><div><strong>{a.action?.replaceAll('_', ' ') || 'Activity'}</strong><p>{a.email || a.userId || 'Account'}</p></div><time>{shortDate(a.timestamp)}</time></div>) : <Empty title={c('No recorded activity yet.', 'لا يوجد نشاط مسجل بعد.')}/>}</section><section className="ac-access-card"><span className="ac-row-icon"><Settings2 size={22}/></span><div><span className="ac-eyebrow">{c('PLATFORM CONTROLS', 'إعدادات المنصة')}</span><h2>{c('Keep operations in focus.', 'تحكم واضح في التشغيل.')}</h2><p>{c('Manage maintenance, announcements and data exports in one place.', 'إدارة الصيانة والإعلانات وتصدير البيانات من مكان واحد.')}</p><button className="ac-text-button" onClick={() => navigate('platform')}>{c('Open platform', 'إدارة المنصة')}<ArrowUpRight size={15}/></button></div></section></div>
   </>}
   {tab === 'requests' && <section className="ac-panel"><div className="ac-section-heading"><div><h2>{c('Requests & referrals', 'الطلبات والإحالات')}</h2><p>{c('All pending requests and the latest 50 records from each queue.', 'كل الطلبات المعلقة وآخر 50 سجلًا من كل قائمة.')}</p></div><Badge tone="warm">{blocked(['requests', 'claims']) ? '—' : pending} {c('pending', 'معلق')}</Badge></div>{blocked(['requests', 'claims']) ? unavailableView(['requests', 'claims']) : <>{toolbar(c('Search account or request…', 'ابحث عن حساب أو طلب…'), [['pending', 'Pending review'], ['approved', 'Approved'], ['rejected', 'Rejected'], ['all', 'All statuses']])}{requests.length ? queueRows(windowRows(requests)) : <Empty title={c('No matching requests.', 'لا توجد طلبات مطابقة.')}/>}<Pager page={page} total={requests.length} onChange={setPage}/></>}</section>}
   {tab === 'people' && <section className="ac-panel"><div className="ac-section-heading"><div><h2>{c('People & access', 'المستخدمون والصلاحيات')}</h2><p>{c('Find an account, review its plan, or manage access.', 'ابحث عن حساب، راجع باقته، وتحكم في صلاحياته.')}</p></div><Users size={21}/></div>{blocked(['users', 'bans']) ? unavailableView(['users', 'bans']) : <>{toolbar(c('Search name, email or account ID…', 'ابحث بالاسم أو البريد أو رقم الحساب…'), [['all', 'All accounts'], ['pro', 'Pro Analyst'], ['enterprise', 'SOC Enterprise'], ['free', 'Stealth'], ['suspended', 'Suspended']])}<div className="ac-table-wrap"><table className="ac-table"><thead><tr><th>{c('Account', 'الحساب')}</th><th>{c('Plan', 'الباقة')}</th><th>{c('Access', 'الحالة')}</th><th>{c('Joined', 'تاريخ الانضمام')}</th><th><span className="ac-sr-only">Actions</span></th></tr></thead><tbody>{windowRows(people).map(u => <tr key={u.id}><td><div className="ac-person"><span className="ac-avatar">{String(u.name || u.email || 'U').slice(0, 2).toUpperCase()}</span><div><strong>{identity(u)}</strong><small>{u.name && u.email ? u.name : u.id}</small></div></div></td><td><Badge tone={effectiveTier(u) !== 'free' ? 'lime' : ''}>{planName(effectiveTier(u))}</Badge></td><td><span className="ac-status" data-warning={suspended.has(u.id)}>{suspended.has(u.id) ? c('Suspended', 'موقوف') : c('Allowed', 'متاح')}</span></td><td className="ac-date">{shortDate(u.createdAt)}</td><td><button className="ac-text-button" aria-label={`Manage ${identity(u)}`} onClick={() => open({ kind: 'person', row: u })}>{c('Manage', 'إدارة')}<ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div>{!people.length && <Empty title={c('No matching accounts.', 'لا توجد حسابات مطابقة.')}/>}<Pager page={page} total={people.length} onChange={setPage}/></>}</section>}
   {tab === 'support' && <section className="ac-panel"><div className="ac-section-heading"><div><h2>{c('Support inbox', 'صندوق الدعم')}</h2><p>{c('Read the conversation, reply, and resolve.', 'راجع المحادثة، أرسل ردك، وأغلق التذكرة بعد الحل.')}</p></div><Badge>{blocked(['tickets']) ? '—' : waiting} {c('open', 'مفتوحة')}</Badge></div>{blocked(['tickets']) ? unavailableView(['tickets']) : <>{toolbar(c('Search subject or email…', 'ابحث بالعنوان أو البريد…'), [['all', 'All tickets'], ['open', 'Awaiting reply'], ['replied', 'Replied'], ['closed', 'Closed']])}{windowRows(tickets).map(t => <button className="ac-ticket-row" key={t.id} onClick={() => open({ kind: 'ticket', row: t })}><span className="ac-row-icon"><MessageSquare size={18}/></span><div className="ac-row-main"><strong>{t.subject || 'Support request'}</strong><small>{t.email || t.userId} · {shortDate(t.createdAt)}</small></div><Badge tone={t.status === 'open' ? 'warm' : ''}>{t.status}</Badge><ArrowUpRight size={16}/></button>)}{!tickets.length && <Empty title={c('No matching tickets.', 'لا توجد تذاكر مطابقة.')}/>}<Pager page={page} total={tickets.length} onChange={setPage}/></>}</section>}
   {tab === 'promotions' && <section className="ac-panel"><div className="ac-section-heading"><div><h2>{c('Promotions', 'العروض')}</h2><p>{c('Create offers and pause codes when a campaign ends.', 'أنشئ العروض وأوقف الأكواد عند انتهاء الحملة.')}</p></div><button className="ac-primary" disabled={blocked(['promos'])} onClick={() => open({ kind: 'promo-new' })}><Plus size={16}/>{c('New code', 'كود جديد')}</button></div>{blocked(['promos']) ? unavailableView(['promos']) : <>{toolbar(c('Find a promo code…', 'ابحث عن كود…'), [['all', 'All codes'], ['active', 'Active'], ['paused', 'Paused']])}<div className="ac-promo-grid">{windowRows(promos).map(p => <article key={p.id}><div><Tag size={18}/><Badge tone={p.active ? 'lime' : ''}>{p.active ? 'Active' : 'Paused'}</Badge></div><h3>{p.code || p.id}</h3><p><strong>{p.discount}%</strong> off · {planName(p.targetTier)}</p><button className="ac-text-button" onClick={() => open({ kind: 'promo-state', row: p })}>{p.active ? c('Pause code', 'إيقاف الكود') : c('Enable code', 'تفعيل الكود')}<ArrowUpRight size={14}/></button></article>)}</div>{!promos.length && <Empty title={c('No matching promotions.', 'لا توجد عروض مطابقة.')}/>}<Pager page={page} total={promos.length} onChange={setPage}/></>}</section>}
   {tab === 'platform' && <AdminPlatform data={data} errors={errors} panel={panel} setPanel={p => navigate('platform', p)} settings={settings} setSettings={setSettings} message={message} setMessage={setMessage} open={open} unavailable={unavailableView} c={c}/>}
   </div>}
   <div className="ac-footer"><span><ShieldCheck size={13}/>{c('Administrator workspace', 'مساحة عمل المسؤول')}</span><span>{updatedAt ? `${c('Last refreshed', 'آخر تحديث')} ${updatedAt.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : c('Waiting for data', 'بانتظار البيانات')}</span></div>
  </>}
 </div>
 {dialog && <AdminDialog dialog={dialog} busy={busy} error={formError} close={() => setDialog(null)} run={run} users={userMap} bans={activeBans} settings={settings} previousSettings={data.settings} message={message} c={c}/>}
 </div>;
}
