import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
const state = vi.hoisted(() => ({ data: {} as any, errors: {} as any, accessError: '', save: vi.fn(async(...args: any[])=>({auditRecorded:true})), refresh: vi.fn(async()=>{}) }));
vi.mock('../lib/firebase',()=>({auth:{currentUser:{uid:'admin'}},db:{},ADMIN_EMAIL:'owner@example.com',logActivity:vi.fn(),calculateEntitlementGrant:vi.fn()}));
vi.mock('../contexts/LanguageContext',()=>({useLanguage:()=>({lang:'en',dir:'ltr'})}));
vi.mock('../hooks/useAdminCenter',()=>({useAdminCenter:()=>({data:state.data,errors:state.errors,loading:false,accessError:state.accessError,updatedAt:new Date('2026-09-11'),refresh:state.refresh})}));
vi.mock('../lib/adminControl',async importOriginal=>({...await importOriginal<any>(),decideRequest:(...args:any[])=>state.save(...args),decideClaim:(...args:any[])=>state.save(...args),saveSettings:(...args:any[])=>state.save(...args),savePromo:(...args:any[])=>state.save(...args)}));
import AdminDashboard from './AdminDashboard';
import { exportAdminRecords } from './admin/AdminPlatform';
beforeEach(()=>{state.data={users:Array.from({length:11},(_,i)=>({id:'u'+i,email:`person${i}@example.com`,name:`Person ${i}`,tier:'free',createdAt:'2026-09-01'})),bans:[],requests:[{id:'request1',userId:'u0',kind:'subscription',tier:'pro',status:'pending',createdAt:'2026-09-10'}],claims:[],tickets:[],promos:[],activity:[],settings:{maintenanceMode:false,aiMaintenanceMode:false},announcements:[]};state.errors={};state.accessError='';state.save.mockReset().mockResolvedValue({auditRecorded:true});state.refresh.mockClear();});
afterEach(cleanup);
it('starts with a compact six-section overview and does not fabricate financial or session metrics',()=>{render(<AdminDashboard/>);expect(within(screen.getByRole('navigation',{name:'Administration sections'})).getAllByRole('button')).toHaveLength(6);expect(screen.getByText('Your review queue')).toBeTruthy();expect(screen.queryByText('Monthly MRR')).toBeNull();expect(screen.queryByText('Live sessions')).toBeNull();expect(state.save).not.toHaveBeenCalled();});
it('searches accounts and paginates the roster, including no-results recovery',()=>{render(<AdminDashboard/>);fireEvent.click(screen.getByRole('button',{name:'People'}));expect(screen.getAllByRole('button',{name:/Manage person/})).toHaveLength(8);fireEvent.click(screen.getByRole('button',{name:'Next page'}));expect(screen.getAllByRole('button',{name:/Manage person/})).toHaveLength(3);fireEvent.change(screen.getByRole('textbox',{name:/Search name/}),{target:{value:'person10@'}});expect(screen.getAllByRole('button',{name:/Manage person/})).toHaveLength(1);fireEvent.change(screen.getByRole('textbox',{name:/Search name/}),{target:{value:'no one'}});expect(screen.getByText('No matching accounts.')).toBeTruthy();});
it('requires an eligibility confirmation and note, prevents duplicate submissions and preserves failed review input',async()=>{
 let reject!: (error:Error)=>void;state.save.mockImplementationOnce(()=>new Promise((_,r)=>{reject=r;}));render(<AdminDashboard/>);fireEvent.click(screen.getByRole('button',{name:'Review'}));const dialog=within(screen.getByRole('dialog'));const submit=dialog.getByRole('button',{name:'Confirm approval'});expect(submit).toBeDisabled();
 fireEvent.click(dialog.getByRole('checkbox'));fireEvent.change(dialog.getByRole('textbox',{name:'Decision note'}),{target:{value:'Payment receipt checked'}});fireEvent.click(submit);fireEvent.click(submit);expect(state.save).toHaveBeenCalledTimes(1);expect(dialog.getByRole('button',{name:'Close dialog'})).toBeDisabled();reject(Error('Payment record changed'));await screen.findByText('Payment record changed');expect(dialog.getByRole('textbox',{name:'Decision note'})).toHaveValue('Payment receipt checked');expect(screen.queryByText('Decision saved.')).toBeNull();
 fireEvent.click(submit);await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());expect(screen.getByRole('status')).toHaveTextContent('Decision saved.');expect(state.refresh).toHaveBeenCalledOnce();
});
it('saves settings only after review and preserves a failed save',async()=>{
 state.save.mockRejectedValueOnce(Error('Another administrator changed these settings.'));render(<AdminDashboard/>);fireEvent.click(screen.getByRole('button',{name:'Platform'}));fireEvent.click(screen.getByRole('switch',{name:'Workspace maintenance'}));expect(state.save).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Review changes'}));expect(state.save).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Save settings'}));await screen.findByRole('alert');expect(screen.getByRole('dialog')).toBeTruthy();expect(state.save.mock.calls[0][0]).toEqual({maintenanceMode:true,aiMaintenanceMode:false});
});
it('shows unavailable data as an error rather than an empty account list',()=>{state.errors={users:'permission-denied'};render(<AdminDashboard/>);fireEvent.click(screen.getByRole('button',{name:'People'}));expect(screen.getByRole('alert')).toHaveTextContent('This section is unavailable');expect(screen.queryByText('No matching accounts.')).toBeNull();expect(screen.queryByRole('table')).toBeNull();});
it('blocks the entire console when the session is not authorized',()=>{state.accessError='A verified administrator session is required.';render(<AdminDashboard/>);expect(screen.queryByRole('navigation')).toBeNull();expect(screen.getByRole('alert')).toHaveTextContent('Administrator access required');});
it('keeps announcements as drafts until explicitly confirmed and restores keyboard focus on dismissal',()=>{render(<AdminDashboard/>);fireEvent.click(screen.getByRole('button',{name:'Platform'}));fireEvent.click(screen.getByRole('button',{name:'Announcements'}));fireEvent.change(screen.getByRole('textbox',{name:'Your message'}),{target:{value:'An update for members'}});const trigger=screen.getByRole('button',{name:'Preview announcement'});trigger.focus();fireEvent.click(trigger);expect(within(screen.getByRole('dialog')).getByText('An update for members')).toBeTruthy();expect(state.save).not.toHaveBeenCalled();fireEvent.keyDown(screen.getByRole('dialog'),{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull();expect(document.activeElement).toBe(trigger);});
it('exports the selected dataset using safe account fields, never authentication secrets',()=>{const result=exportAdminRecords('users',[{id:'u',email:'one@example.com',tier:'pro',mfaSecret:'sensitive',apiKey:'key',arbitrary:'private'}]);expect(result.records).toEqual([{id:'u',email:'one@example.com',tier:'pro'}]);const bans=exportAdminRecords('bans',[{id:'u',reason:'abuse',active:true}]);expect(bans.records[0]).toEqual({id:'u',reason:'abuse',active:true});});
