import {useEffect,useState} from 'react';
import {collection,query,where,orderBy,onSnapshot} from 'firebase/firestore';
import {auth,db} from '../lib/firebase';
import {Mail,KeyRound,Link,Grid2X2,ArrowUpRight} from 'lucide-react';
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip,PieChart,Pie,Cell,RadarChart,Radar,PolarGrid,PolarAngleAxis} from 'recharts';
import AiQuotaMeter from './AiQuotaMeter';
import {computeTier} from './BadgeSystem';
import '../styles/focus-dashboard.css';
type Kind='email'|'password'|'url';
type Scan={id:string;type:string;target:string;risk:string;score:number|null;date:Date|null};
const tools=[['email','Email exposure'],['password','Password check'],['url','Suspicious link'],['message','Message phishing'],['domain','Domain lookup']] as const;
export default function Dashboard({onNavigate,onStart}:{onNavigate:(tab:any)=>void;onStart?:(kind:Kind,value:string)=>void}){
 const [kind,setKind]=useState<Kind>('email'),[input,setInput]=useState(''),[all,setAll]=useState(false),[scans,setScans]=useState<Scan[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false);
 useEffect(()=>{if(!auth.currentUser){setLoading(false);return}return onSnapshot(query(collection(db,'scans'),where('userId','==',auth.currentUser.uid),orderBy('createdAt','desc')),snapshot=>{setScans(snapshot.docs.map(d=>{const s=d.data();return {id:d.id,type:s.type||'unknown',target:s.type==='password'?'Password check':s.target||s.emailScanned||'Untitled check',risk:String(s.riskLevel||'Unknown').toUpperCase(),score:typeof s.securityScore==='number'&&Number.isFinite(s.securityScore)?Math.max(0,Math.min(100,s.securityScore)):null,date:s.createdAt?.toDate?.()||null}}));setLoading(false);setError(false)},()=>{setLoading(false);setError(true)})},[]);
 const valid=scans.filter(s=>s.score!==null);const score=valid.length?Math.round(valid.reduce((n,s)=>n+s.score!,0)/valid.length):null;
 const risk=['HIGH','MEDIUM','LOW','UNKNOWN'].map((r,i)=>({name:r,value:scans.filter(s=>r==='UNKNOWN'?!['HIGH','MEDIUM','LOW'].includes(s.risk):s.risk===r).length,color:['#dfad86','#d2cd89','#b7ff72','#779387'][i]})).filter(x=>x.value);
 const timeline=(monthly:boolean)=>Array.from({length:monthly?12:7},(_,i)=>{const d=new Date();if(monthly)d.setMonth(i,1);else d.setDate(d.getDate()-6+i);const matching=scans.filter(s=>s.date&&s.date.getFullYear()===d.getFullYear()&&s.date.getMonth()===d.getMonth()&&(monthly||s.date.getDate()===d.getDate()));return {name:d.toLocaleDateString('en',{[monthly?'month':'weekday']:'short'}),checks:matching.length,flagged:matching.filter(s=>s.risk==='HIGH').length}});
 const types=[...tools,['social','Social OSINT (previous)']].map(([type,name])=>({name,value:scans.filter(s=>s.type===type||(type==='social'&&s.type==='social_osint')).length})).filter(s=>s.value);
 const empty=<p className="fd-empty">{loading?'Loading your checks…':error?'Reports could not be loaded. Please refresh to retry.':'Your charts will appear after your first saved check.'}</p>;
 const chart=(monthly=false)=><ResponsiveContainer width="100%" height={205}><AreaChart data={timeline(monthly)}><XAxis dataKey="name" tick={{fill:'#8d9f86',fontSize:10}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} width={25} tick={{fill:'#8d9f86',fontSize:10}}/><Tooltip contentStyle={{background:'#152013',border:'1px solid #536946',borderRadius:8,color:'#edf2e9'}}/><Area type="monotone" dataKey="checks" stroke="#b7ff72" fill="#b7ff72" fillOpacity={.08}/><Area type="monotone" dataKey="flagged" stroke="#dfad86" fill="#dfad86" fillOpacity={.07}/></AreaChart></ResponsiveContainer>;
 return <main className="focus-dashboard" lang="en" dir="ltr"><section className="fd-hero"><div className="fd-orb">{kind==='email'?<Mail/>:kind==='password'?<KeyRound/>:<Link/>}</div><span className="fd-eyebrow">YOUR SPACE TO LOOK CLOSER</span><h1>What would you like<br/>to <em>understand?</em></h1><p>Start with a question. Find the right check.</p><div className="fd-chips">{(['email','password','url'] as Kind[]).map(k=><button key={k} aria-pressed={kind===k} onClick={()=>{setKind(k);setInput('')}}>{k==='url'?'Link':k[0].toUpperCase()+k.slice(1)}</button>)}</div><form className="fd-search" onSubmit={e=>{e.preventDefault();onStart?onStart(kind,input):onNavigate(kind);setInput('')}}><input aria-label={kind==='url'?'Link to check':kind+' to check'} type={kind==='url'?'url':kind} autoComplete="off" value={input} onChange={e=>setInput(e.target.value)} required placeholder={kind==='email'?'Enter an email address':kind==='password'?'Enter a password to check':'https://example.com'}/><button type="submit">Continue to check <ArrowUpRight size={16}/></button></form><small>Review the tool and start your scan on the next screen.</small></section>
 <section className="fd-posture"><div className="fd-score">{loading||error?'—':score??'—'}</div><div><span className="fd-eyebrow">YOUR SAVED RESULTS</span><h2>{loading?'Loading your workspace':error?'Your reports are unavailable':scans.length?'A clearer view of your findings.':'Your next step starts here.'}</h2><p>{score!==null?'Average of scored checks. An assessment, not a security guarantee.':'Run a check to start building your personal overview.'}</p></div><div className="fd-metrics"><div><strong>{loading||error?'—':scans.length}</strong><small>CHECKS</small></div><div><strong>{loading||error||!scans.length?'—':computeTier(scans.length).name}</strong><small>TIER</small></div><div><strong>{loading||error?'—':scans.filter(s=>s.risk==='HIGH').length}</strong><small>HIGH RISK</small></div></div></section>
 <AiQuotaMeter/><div className="fd-quick">{[[Mail,'email','Email exposure'],[KeyRound,'password','Password check'],[Link,'url','Suspicious link']].map(([Icon,id,label]:any)=><button key={id} onClick={()=>onNavigate(id)}><Icon size={24}/><strong>{label}</strong><small>Open tool ↗</small></button>)}<button onClick={()=>setAll(!all)} aria-expanded={all} aria-controls="fd-all-tools"><Grid2X2 size={24}/><strong>More tools</strong><small>Explore your toolkit ↗</small></button></div>{all&&<section className="fd-panel fd-directory" id="fd-all-tools"><h2>Your toolkit</h2><div>{tools.map(([id,label])=><button key={id} onClick={()=>onNavigate(id)}>{label}<ArrowUpRight size={15}/></button>)}</div></section>}
 <div className="fd-grid"><section className="fd-panel"><div className="fd-panel-head"><h2>Continue exploring</h2><button onClick={()=>onNavigate('history')}>Your history ↗</button></div>{!scans.length?empty:scans.slice(0,3).map(s=><div className="fd-row" key={s.id}><div><strong>{s.target}</strong><small>{s.type.replaceAll('_',' ')} · {s.date?.toLocaleDateString('en')||'Date unavailable'}</small></div><button onClick={()=>onNavigate('history')}>View in history ↗</button></div>)}</section><section className="fd-panel"><span className="fd-eyebrow">YOUR NEXT STEPS</span><h2>Turn insight into action.</h2><p>Review the sources and limitations in your saved reports.</p><p>Use unique passwords and enable two-factor authentication.</p><button className="fd-text-button" onClick={()=>onNavigate('password')}>Review password security ↗</button></section></div>
 <div className="fd-grid"><section className="fd-panel"><h2>Activity timeline</h2><p>Last seven days</p>{scans.length?chart():empty}</section><section className="fd-panel"><h2>Risk distribution</h2>{!scans.length?empty:<><ResponsiveContainer width="100%" height={190}><PieChart><Pie data={risk} dataKey="value" innerRadius={55} outerRadius={78}>{risk.map(r=><Cell key={r.name} fill={r.color}/>)}</Pie><Tooltip contentStyle={{background:'#152013',border:'1px solid #536946'}}/></PieChart></ResponsiveContainer><div className="fd-legend">{risk.map(r=><span key={r.name} style={{color:r.color}}>{r.name} · {r.value}</span>)}</div></>}</section></div>
 <div className="fd-grid"><section className="fd-panel"><h2>Yearly check timeline</h2><p>Saved activity in {new Date().getFullYear()}</p>{scans.length?chart(true):empty}</section><section className="fd-panel"><h2>Checks by tool</h2><p>Saved report counts, not live attack detection.</p>{types.length>=3?<ResponsiveContainer width="100%" height={220}><RadarChart data={types}><PolarGrid stroke="#415337"/><PolarAngleAxis dataKey="name" tick={{fill:'#acbda2',fontSize:10}}/><Radar dataKey="value" stroke="#b7ff72" fill="#b7ff72" fillOpacity={.15}/><Tooltip/></RadarChart></ResponsiveContainer>:types.length?types.map(t=><div className="fd-row" key={t.name}>{t.name}<strong>{t.value}</strong></div>):empty}</section></div>
 </main>;
}
