import React,{useState,useEffect,useRef,useCallback,useMemo} from 'react';
import {useReducedMotion} from 'motion/react';
import {RefreshCw,RotateCcw,ZoomIn,ZoomOut,Pause,Play,Globe,Search,ExternalLink,ArrowLeft,ArrowRight,ShieldAlert} from 'lucide-react';
import {useLanguage} from '../contexts/LanguageContext';
import {fetchThreatFeed,ThreatFeedResponse,ThreatIndicator} from '../lib/threatFeed';
import {canMapIndicator} from '../lib/globeProjection';
import ThreatGlobe from './ThreatGlobe';
import '../styles/focus-threat.css';
export default function ThreatMap3D(){
 const {lang,dir}=useLanguage(),copy=(en:string,ar:string)=>lang==='ar'?ar:en;const reduced=useReducedMotion();
 const [feed,setFeed]=useState<ThreatFeedResponse|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[paused,setPaused]=useState(false),[zoom,setZoom]=useState(1),[reset,setReset]=useState(0),[selected,setSelected]=useState<ThreatIndicator|null>(null),[family,setFamily]=useState('all'),[status,setStatus]=useState('all'),[search,setSearch]=useState(''),[page,setPage]=useState(0);
 const inFlight=useRef(false),mounted=useRef(false);
 const load=useCallback(async()=>{if(inFlight.current)return;inFlight.current=true;setLoading(true);setError('');try{const data=await fetchThreatFeed();if(mounted.current){if(!Array.isArray(data.indicators))throw Error('Invalid threat feed response');setFeed(data)}}catch(err){if(mounted.current)setError(err instanceof Error?err.message:'Feed unavailable')}finally{inFlight.current=false;if(mounted.current)setLoading(false)}},[]);
 useEffect(()=>{mounted.current=true;load();const timer=setInterval(()=>{if(!document.hidden)load()},60000);return()=>{mounted.current=false;clearInterval(timer)}},[load]);
 const indicators=feed?.indicators||[];
 const families=useMemo(()=>Array.from(new Set(indicators.map(i=>i.malware).filter(Boolean))).sort(),[feed]);
 const filtered=useMemo(()=>indicators.filter(i=>(family==='all'||i.malware===family)&&(status==='all'||i.status===status)&&[i.ip,i.countryName,i.country,i.malware,i.asName].some(v=>(v||'').toLowerCase().includes(search.trim().toLowerCase()))),[feed,family,status,search]);
 useEffect(()=>{setPage(0);setSelected(null)},[family,status,search]);
 useEffect(()=>{if(selected){const next=filtered.find(i=>i.id===selected.id);setSelected(next||null)}setPage(p=>Math.min(p,Math.max(0,Math.ceil(filtered.length/12)-1)))},[feed]);
 const choose=(i:ThreatIndicator)=>{setSelected(i);setPaused(true)};
 const mapped=filtered.filter(canMapIndicator),pages=Math.max(1,Math.ceil(filtered.length/12));
 const formatDate=(v?:string|null)=>v&&!Number.isNaN(Date.parse(v))?new Date(v).toLocaleString(lang==='ar'?'ar-EG':'en-US'):'—';
 return <div className="focus-threat" dir={dir}><header className="tv-header"><div><span className="tv-eyebrow">JOESCAN / THREAT INTELLIGENCE</span><h1>3D Threat Visualizer</h1><p>{copy('Explore the infrastructure behind the signals.','استكشف البنية التحتية وراء مؤشرات التهديد.')}</p></div><button className="tv-button" disabled={loading} onClick={load}><RefreshCw size={16} className={loading?'animate-spin':''}/>{copy('Refresh feed','تحديث البيانات')}</button></header>
 <div className="tv-metrics">{[[copy('Indicators','المؤشرات'),feed?indicators.length:'—'],[copy('Reported online','نشط حسب المصدر'),feed?indicators.filter(i=>i.status==='online').length:'—'],[copy('Countries mapped','دول على الخريطة'),feed?new Set(indicators.filter(canMapIndicator).map(i=>i.country)).size:'—'],[copy('Malware families','عائلات البرمجيات الخبيثة'),feed?families.length:'—']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
 {error&&<div className="tv-error" role="alert"><ShieldAlert size={18}/><div>{feed?copy('Refresh failed. Showing the last available feed.','فشل التحديث. تُعرض آخر بيانات متاحة.'):copy('The threat feed could not be loaded.','تعذر تحميل مؤشرات التهديد.')}<small>{error}</small></div></div>}
 <div className="tv-layout"><section className="tv-stage"><div className="tv-stage-heading"><span><Globe size={15}/>{copy('Infrastructure view','عرض البنية التحتية')}</span><span className="tv-eyebrow">{loading?copy('UPDATING','جاري التحديث'):feed?copy('SOURCE SNAPSHOT','بيانات المصدر'):copy('NO DATA','لا توجد بيانات')}</span></div><ThreatGlobe indicators={filtered} paused={paused||!!reduced} zoom={zoom} resetKey={reset} selected={selected} onSelect={choose} label={copy('Threat globe. Drag or use arrow keys to rotate. Select markers or use the indicator list.','اسحب أو استخدم الأسهم لتدوير الكرة. اختر نقطة أو استخدم قائمة المؤشرات.')}/><div className="tv-stage-bottom"><p>{copy('Drag to rotate · Select a marker','اسحب للتدوير · اضغط على نقطة')}</p><div className="tv-controls"><button aria-label="Zoom out" disabled={zoom<=.7} onClick={()=>setZoom(z=>Math.max(.7,z-.15))}><ZoomOut size={16}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" disabled={zoom>=1.7} onClick={()=>setZoom(z=>Math.min(1.7,z+.15))}><ZoomIn size={16}/></button><button aria-label="Reset view" onClick={()=>{setZoom(1);setReset(r=>r+1);setSelected(null)}}><RotateCcw size={16}/></button><button aria-label={paused?'Resume rotation':'Pause rotation'} aria-pressed={paused||!!reduced} disabled={!!reduced} onClick={()=>setPaused(p=>!p)}>{paused||reduced?<Play size={16}/>:<Pause size={16}/>}</button></div></div><div className="tv-legend"><span><i/>{copy('Online','نشط')}</span><span><i/>{copy('Offline / historical','متوقف / سابق')}</span><span>{mapped.length} / {filtered.length} {copy('mapped','على الخريطة')}</span></div></section>
 <aside className="tv-details"><span className="tv-eyebrow">{copy('INDICATOR DETAILS','تفاصيل المؤشر')}</span>{selected?<><h2 dir="ltr">{selected.ip}{selected.port?':'+selected.port:''}</h2><span className="tv-status" data-online={selected.status==='online'}>{selected.status}</span><dl>{[[copy('Malware','البرمجية'),selected.malware],[copy('Country','الدولة'),selected.countryName],[copy('Network','الشبكة'),selected.asName],[copy('ASN','رقم الشبكة'),selected.asNumber?`AS${selected.asNumber}`:'—'],[copy('Hostname','اسم المضيف'),selected.hostname],[copy('First seen','أول رصد'),formatDate(selected.firstSeen)],[copy('Last online','آخر نشاط'),formatDate(selected.lastOnline)]].map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value||'—'}</dd></div>)}</dl><a href={'https://feodotracker.abuse.ch/browse/host/'+encodeURIComponent(selected.ip)+'/'} target="_blank" rel="noopener noreferrer">{copy('Inspect source','فحص المصدر')}<ExternalLink size={14}/></a></>:<div className="tv-detail-empty"><Globe size={38}/><h2>{copy('A signal worth a closer look.','نظرة أقرب لكل مؤشر.')}</h2><p>{copy('Select a marker or an indicator below to inspect its source, network, and history.','اختر نقطة على الخريطة أو مؤشراً من القائمة لعرض مصدره وشبكته وتاريخه.')}</p></div>}<p className="tv-caveat">{copy('Country markers are approximate centroids, not host locations or attack paths. This feed does not describe attacks on your account.','النقاط تمثل مراكز دول تقريبية وليست مواقع الخوادم أو مسارات الهجمات. هذه البيانات لا تصف هجمات على حسابك.')}</p></aside></div>
 <section className="tv-feed"><div className="tv-feed-top"><h2>{copy('Explore the indicators','استكشف المؤشرات')}</h2><span>{feed?.source||'abuse.ch Feodo Tracker'} · {formatDate(feed?.updatedAt)}</span></div><div className="tv-filters"><label><Search size={16}/><input aria-label="Search indicators" value={search} onChange={e=>setSearch(e.target.value)} placeholder={copy('Search IP, country, network…','ابحث عن IP أو دولة أو شبكة…')}/></label><select aria-label="Filter malware" value={family} onChange={e=>setFamily(e.target.value)}><option value="all">{copy('All malware','كل البرمجيات')}</option>{families.map(f=><option key={f}>{f}</option>)}</select><select aria-label="Filter status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{copy('All statuses','كل الحالات')}</option><option value="online">Online</option><option value="offline">Offline</option></select></div><div className="tv-list">{filtered.slice(page*12,page*12+12).map(i=><button key={i.id} className="tv-row" aria-pressed={selected?.id===i.id} onClick={()=>choose(i)}><span><strong dir="ltr">{i.ip}{i.port?':'+i.port:''}</strong><small>{i.countryName} · {i.asName||'—'}</small></span><span>{i.malware}</span><span className="tv-status" data-online={i.status==='online'}>{i.status}</span><ArrowRight size={15}/></button>)}</div>{!filtered.length&&<p className="tv-list-empty" role="status">{loading?copy('Loading indicators…','جاري التحميل…'):error&&!feed?copy('Refresh to retry loading the feed.','اضغط تحديث لإعادة المحاولة.'):copy('No indicators match this view.','لا توجد مؤشرات مطابقة.')}</p>}<footer><span>{filtered.length?`${page*12+1}–${Math.min((page+1)*12,filtered.length)} / ${filtered.length}`:'0'} {copy('indicators','مؤشرات')}</span><div><button className="tv-button" aria-label="Previous page" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ArrowLeft size={15}/></button><span>{page+1} / {pages}</span><button className="tv-button" aria-label="Next page" disabled={page+1>=pages} onClick={()=>setPage(p=>p+1)}><ArrowRight size={15}/></button></div></footer></section></div>;
}
